# Programación con arrays: introducción a Numpy

## Objetivos

**1.** Conocer las estructuras de datos y su implementación en Python. <br>
**2.** Utilizar arreglos y operaciones básicas y vectorizadas en `numpy`. <br>

En programación, una librería es un conjunto de funcionalidades que ya están escritas y podemos llamar para utilizarlas en nuestros programas. La librería `numpy` nos ofrece la posibilidad de crear arreglos y matrices multidimensionales, lo cual nos permite estructurar datos, con el fin de analizarlos más adelante.

## 1. Librería `numpy`
`numpy` es una librería de uso abierto para el lenguaje de Python que permite crear vectores (arreglos) y matrices multidimensionales. Esta librería nos ofrece la posibilidad de llevar a cabo operaciones matemáticas de alto nivel y con una gran velocidad.<br>
<br>
Importamos la libería `numpy` utilizando el nombre `np` (su alias más frecuentemente usado):

In [1]:
import numpy as np

In [2]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


### 1.1. Declaración, consulta y operaciones básicas con arreglos
Los arreglos son la estructura principal que nos provee `numpy`. Estos nos permiten guardar información en un contenedor para aplicar operaciones sobre ellos posteriormente. Los arreglos de `numpy` tienen más funcionalidades que las listas nativas de Python.

#### Declaración

Para declarar un arreglo utilizamos el método `array` del paquete `numpy`.

In [3]:
# Ejemplo 1
arreglo = np.array([1,2,3,4])
print(arreglo)

[1 2 3 4]


In [4]:
# Ejemplo 2
np_cero = np.zeros(10, dtype ='int')
np_cero

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# Ejemplo 3
np_relleno = np.full(3, 256)
np_relleno

array([256, 256, 256])

In [6]:
# Ejemplo 4

# Rangos
np_rango = np.arange(3,10, step = 3)
print(np_rango)
print(type(np_rango))   #tambièn puede usarse el método dtype

# Varias Dimensiones y Aleatoriedad
np_dimensional = np.random.randint(50, size=(3, 4))  # primero filas, luego columnas
np_dimensional

[3 6 9]
<class 'numpy.ndarray'>


array([[13, 46, 38, 46],
       [13, 12, 24, 10],
       [25, 12, 37, 41]])

#### Propiedades

Son métodos o características de los elementos `array` que forma parte del paquete `numpy`.

In [7]:
# Dimensiones
dimensiones = np_relleno.ndim
print('La dimensión del "array" np_relleno es de:', dimensiones)

La dimensión del "array" np_relleno es de: 1


In [8]:
# Forma o Shape 
forma = np_dimensional.shape              #Muy útil para verificar dimensionalidad matricial
print('La forma del "array" es de:', forma)

La forma del "array" es de: (3, 4)


In [10]:
# Tamaño
tamaño = np_dimensional.size
print('La forma del "array" es de:', forma)

La forma del "array" es de: (3, 4)


#### Consulta

Accedemos a un elemento en un arreglo con la misma sintaxis que consultamos listas. A continuación vemos un ejemplo de cómo acceder al primer elemento del `arreglo`.

In [11]:
elemento1 = arreglo[0]
print("El primer elemento del arreglo es " + str(elemento1) + ".")

El primer elemento del arreglo es 1.


In [14]:
elemento_final = arreglo[3]
print("El último elemento del arreglo es " + str(elemento_final) + ".")

El último elemento del arreglo es 4.


In [15]:
# Acceso en arreglos de varias dimensiones
# Consultamos el elemento contenido en la tercera fila y segunda columna del arreglo matricial np_dimensional

np_dimensional[2,1]   #Recordar que los índices se inician en 0.

12

#### Rebanado

Utilizamos la misma notación de las listas nativas de Python para acceder a una porción de un arreglo. A continuación vemos un ejemplo de cómo acceder a los últimos dos elementos del `arreglo`.

In [16]:
# Ejemplo 1
# Últimos dos elementos del array arreglo

porcion_arreglo = arreglo[-2:]
print(porcion_arreglo)

[3 4]


In [17]:
# Ejemplo 2
# Traer las primeras dos filas y las primeras dos columnas del array np_dimensional
np_dimensional[:2,:2]

array([[13, 46],
       [13, 12]])

#### Operaciones básicas con arreglos: agregar y eliminar elementos

Revisemos como añadir un elemento a un arreglo. Para esto, debemos especificar el arreglo y el elemento que queremos añadir al final del mismo.

In [18]:
arreglo = np.append(arreglo, 5)
print(arreglo)

[1 2 3 4 5]


Ahora, revisamos cómo eliminar un elemento de un arreglo. Para esto, debemos especificar el arreglo y la posición del elemento que queremos eliminar.

In [20]:
# Eliminamos el elemento contenido en posición 1.
arreglo = np.delete(arreglo, 1)
print(arreglo)

[1 4 5]


#### Ejemplo Ajedrez -- Método Reshape

¿Cómo podemos crear una cuadrícula para representar las 64 posiciones de un tablero de ajedrez.

In [21]:
#Creamos el arreglo que contiene los 64 números
Cuadrícula = np.arange(1,65)
print(Cuadrícula)
#Usamos el método reshape para establecer una nueva forma de la cuadrícula
Ajedrez_64 = Cuadrícula.reshape(8,8)
Ajedrez_64

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

### 1.2. Métodos comunes con arreglos en `numpy`

La ventaja de utilizar arreglos de `numpy` es que estos tienen un gran número de métodos que nos permiten llevar a cabo diversos tipos de análisis. A continuación, definimos un arreglo de tipo numérico e implementaremos algunos de los métodos más utilizados.

In [22]:
# Definimos un arreglo.
arreglo = np.array([1,2,3,4])

#### Suma
Calcula la suma de todos los elementos de un arreglo, siempre y cuando todos sean de tipo numerico.

In [23]:
#Sumamos los elementos del arreglo.
suma = arreglo.sum()
print("La suma de todos los elementos es " + str(suma) + ".")

La suma de todos los elementos es 10.


#### Promedio
Calcula el promedio de todos los elementos de un arreglo, siempre y cuando todos sean de tipo numerico.

In [24]:
# Calculamos el promedio del arreglo.
promedio = arreglo.mean()
print("El promedio de todos los elementos es " + str(promedio) + ".")

El promedio de todos los elementos es 2.5.


#### Mediana
Calcula la mediana de todos los elementos de un arreglo, siempre y cuando todos sean de tipo numerico.

In [25]:
# Calculamos la mediana del arreglo.
mediana = np.median(arreglo)
print("El promedio de todos los elementos es " + str(mediana) + ".")

El promedio de todos los elementos es 2.5.


#### Máximo y mínimo
Calcula el máximo y mínimo elemento dentro de un arreglo, respectivamente, siempre y cuando todos los elementos sean de tipo numerico.

In [26]:
maximo = arreglo.max()
print("El máximo elemento es " + str(maximo) + ".")

El máximo elemento es 4.


In [27]:
minimo = arreglo.min()
print("El minimo elemento es " + str(minimo) + ".")

El minimo elemento es 1.


#### Concatenar
Concatena dos o más arreglos en uno.

In [28]:
# Definimos los arreglos a concatenar.
arreglo_1 = np.array([1,2,3,4])
arreglo_2 = np.array([5,6,7,8])

arreglo_concat = np.concatenate((arreglo_1, arreglo_2))

print(arreglo_concat)

[1 2 3 4 5 6 7 8]


#### Separar o Splitting
Consiste en desarmar o partir los arreglos. Puede pensarse como la **operación inversa a la concatenación**

In [30]:
splitted_array = np.split(arreglo_concat, [2])
splitted_array

[array([1, 2]), array([3, 4, 5, 6, 7, 8])]

### 1.3. Operaciones básicas sobre vectores con `numpy`

Otra gran funcionalidad que nos provee `numpy` es la posibilidad de realizar operaciones vectoriales de una manera sencilla y rápida. Para esto, veremos como crear matrices con `numpy`.

#### Matrices

`numpy` provee la posibilidad de crear matrices multidimensionales a las cuales les podemos aplicar múltiples operaciones. La forma de crearlas en `numpy` es la siguiente:

In [31]:
matriz = np.array( [ [1,2,3], [4,5,6] ] )
matriz

array([[1, 2, 3],
       [4, 5, 6]])

Creemos dos matrices para aplicarles algunas operaciones:

In [32]:
mat_1 = np.array([[1,2], [3,4]])
mat_1

array([[1, 2],
       [3, 4]])

In [33]:
mat_2 = np.array([[1,1], [4,4]])
mat_2

array([[1, 1],
       [4, 4]])

Ahora, procedemos a ver operaciones con matrices en `numpy`:

#### Suma término a término
Para sumar cada elemento de `mat_1` con el elemento ubicado en la misma posición de `mat_2`, utilizamos el operador `+`.

In [34]:
suma_matrices = mat_1 + mat_2
suma_matrices

array([[2, 3],
       [7, 8]])

#### Multiplicación término a término
Para multiplicar cada elemento de `mat_1` con el elemento ubicado en la misma posición de `mat_2`, utilizamos el operador `*`.

In [35]:
producto_matrices = mat_1 * mat_2
producto_matrices

array([[ 1,  2],
       [12, 16]])

#### Multiplicación matricial
Para realizar una multiplicación matricial en `numpy` utilizamos el método `dot()`.

In [37]:
# Producto punto.
mat_1_por_mat_2 = mat_1.dot(mat_2)
mat_1_por_mat_2

array([[ 9,  9],
       [19, 19]])

In [38]:
mat_2_por_mat_1 = mat_2.dot(mat_1)
mat_2_por_mat_1

array([[ 4,  6],
       [16, 24]])

#### Matriz transpuesta
Para transponer una matriz en `numpy` utilizamos el método `transpose()`.

In [39]:
trans_matriz = mat_1.transpose()
trans_matriz

array([[1, 3],
       [2, 4]])

#### Expresión lógica término a término
Podemos aplicar los operadores lógicos `&`, `|` y `~` (similares a `and`, `or` y `not`, respectivamente) a dos objetos tipo `array` de `numpy` (que contengan valores de tipo `bool`), con el fin de evaluar término a término la condición lógica.

In [40]:
arreglo_booleano = np.array([True, False, False]) | np.array([True, True, False])
arreglo_booleano

array([ True,  True, False])

### 1.3. Convertir archivos a arreglos de `numpy`
La librería o paquete `numpy` tiene unas útiles funciónes para obtener datos desde archivos. En este caso usaremos el formato `.txt`. <br>

**Nota Importante**: para facilitar el trabajo, el archivo de ejemplo debe estar guardado en su directorio de trabajo, es decir la carpeta en donde está contenido el Jupyter Notebook que están ejecutando.

In [43]:
# datos = np.genfromtxt("Nombre_del_archivo.txt", skip_header = 1, dtype = 'str')
# datos
